substitutions:
  name: tagreader--tester
  friendly_name: Tagreader - Tester

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: ${name}
    password: !secret fallback_password

# Enable Home Assistant API
api:
  encryption:
#    key: "XXX"

ota:
  - platform: esphome
#    password: "YYY"

packages:
  base: github://larcster/esphome_tagreader/tagreader_spi-lolin_s3_mini.yaml@develop # change this to main to get tested code